/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.webverissimo.cadastro.principal;

import br.webverissimo.cadastro.cadastroTelas.Cargos;
import br.webverissimo.cadastro.cadastroTelas.Clientes;
import br.webverissimo.cadastro.cadastroTelas.Departamentos;
import br.webverissimo.cadastro.cadastroTelas.Fornecedores;
import br.webverissimo.cadastro.cadastroTelas.Usuarios;

/**
 *
 * @author livia
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMCadastro = new javax.swing.JMenu();
        jMCargos = new javax.swing.JMenuItem();
        jMDepartamento = new javax.swing.JMenuItem();
        jMUsuario = new javax.swing.JMenuItem();
        jMFornecedores = new javax.swing.JMenuItem();
        jMClientes = new javax.swing.JMenuItem();
        jMOpcoes = new javax.swing.JMenu();
        jMSair = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMCadastro.setText("Cadastros");
        jMCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastroActionPerformed(evt);
            }
        });

        jMCargos.setText("Cargo");
        jMCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCargosActionPerformed(evt);
            }
        });
        jMCadastro.add(jMCargos);

        jMDepartamento.setText("Departamento");
        jMDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMDepartamentoActionPerformed(evt);
            }
        });
        jMCadastro.add(jMDepartamento);

        jMUsuario.setText("Usuário");
        jMUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMUsuarioActionPerformed(evt);
            }
        });
        jMCadastro.add(jMUsuario);

        jMFornecedores.setText("Fornecedores");
        jMFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMFornecedoresActionPerformed(evt);
            }
        });
        jMCadastro.add(jMFornecedores);

        jMClientes.setText("Clientes");
        jMClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMClientesActionPerformed(evt);
            }
        });
        jMCadastro.add(jMClientes);

        jMenuBar1.add(jMCadastro);

        jMOpcoes.setText("Opções");
        jMOpcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMOpcoesActionPerformed(evt);
            }
        });

        jMSair.setText("Sair");
        jMSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSairActionPerformed(evt);
            }
        });
        jMOpcoes.add(jMSair);

        jMenuBar1.add(jMOpcoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMOpcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMOpcoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMOpcoesActionPerformed

    private void jMCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMCadastroActionPerformed

    private void jMCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCargosActionPerformed
     new Cargos().setVisible(true);
     // Chamada do formulário Modal...
     // new Cargos(this, true).setVisible(true);
    }//GEN-LAST:event_jMCargosActionPerformed

    private void jMDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMDepartamentoActionPerformed
     new Departamentos().setVisible(true);
     // Chamada do formulário Modal...
     //  new Departamentos(this, true).setVisible(true);
        
    }//GEN-LAST:event_jMDepartamentoActionPerformed

    private void jMUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMUsuarioActionPerformed
        new Usuarios().setVisible(true);   
    }//GEN-LAST:event_jMUsuarioActionPerformed

    private void jMSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMSairActionPerformed

    private void jMFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMFornecedoresActionPerformed
        // TODO add your handling code here:
        new Fornecedores().setVisible(true);   
    }//GEN-LAST:event_jMFornecedoresActionPerformed

    private void jMClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMClientesActionPerformed
        // TODO add your handling code here:
          new Clientes().setVisible(true);
    }//GEN-LAST:event_jMClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMCadastro;
    private javax.swing.JMenuItem jMCargos;
    private javax.swing.JMenuItem jMClientes;
    private javax.swing.JMenuItem jMDepartamento;
    private javax.swing.JMenuItem jMFornecedores;
    private javax.swing.JMenu jMOpcoes;
    private javax.swing.JMenuItem jMSair;
    private javax.swing.JMenuItem jMUsuario;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
